Gemfile
Gemfile.lock
app/views/devise/confirmations/new.html.erb
app/views/devise/mailer/confirmation_instructions.html.erb
app/views/devise/mailer/email_changed.html.erb
app/views/devise/mailer/password_change.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/mailer/unlock_instructions.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_error_messages.html.erb
app/views/devise/shared/_links.html.erb
app/views/devise/unlocks/new.html.erb
config/environments/development.rb
config/initializers/devise.rb
config/locales/devise.en.yml
config/routes.rb

Closes: #12 
How to evaluate: Check the gemfile. 
I also added all the devise views to the application, can now edit them.

HANDY-25: Add the devise gem

---

app/controllers/customer_controller.rb
app/controllers/worker_controller.rb
app/views/customer/customer_profile.html.erb
app/views/customer/home.html.erb
app/views/worker/worker_home.html.erb
config/routes.rb

Closes #23 
How to Evaluate: After a customer signs in/signs up, the customer should be able to click the 'My Profile' button and be directed to their profile which has their information displayed.
added route, controller action, and view template for customer profile
Additional Changes:
deleted worker home page controller action from customer controller
deleted worker home page view template from controller folder
added controller action  to worker controller and view template for worker home page  to worker folder

HANDY-23: Add a customer personal profile page to the app

---

app/controllers/application_controller.rb
app/views/customers/registrations/new.html.erb
app/views/worker/worker_home.html.erb
app/views/workers/confirmations/new.html.erb
app/views/workers/mailer/confirmation_instructions.html.erb
app/views/workers/mailer/email_changed.html.erb
app/views/workers/mailer/password_change.html.erb
app/views/workers/mailer/reset_password_instructions.html.erb
app/views/workers/mailer/unlock_instructions.html.erb
app/views/workers/passwords/edit.html.erb
app/views/workers/passwords/new.html.erb
app/views/workers/registrations/edit.html.erb
app/views/workers/registrations/new.html.erb
app/views/workers/sessions/new.html.erb
app/views/workers/shared/_error_messages.html.erb
app/views/workers/shared/_links.html.erb
app/views/workers/unlocks/new.html.erb
db/schema.rb

closes #4 
Generated devise worker view, added attributes to customer and worker view page.

HANDY-20 Design the worker sign-up page

---

app/views/customers/sessions/new.html.erb

closes #8 
Added customer sign up header and home page button.

HANDY-21: Add styling to the Customer sign-in page

---

app/controllers/worker_controller.rb
app/views/worker/worker_home.html.erb
app/views/worker/worker_profile.html.erb
config/routes.rb

Closes #11 
added route, controller action, and view template for worker profile; added profile link to worker home page

HANDY-24: Add a worker personal profile page to the app

---

app/controllers/application_controller.rb
app/controllers/worker_controller.rb
app/views/customer/home.html.erb
app/views/worker/worker_directory.html.erb
config/routes.rb
db/seeds.rb

Closes #5 
added route, controller action, and view template for worker directory; added worker directory link to customer home page; added specialty attribute key to application controller; added new worker seed data

HANDY-2: Add a worker registry/worker directory page

---

app/controllers/worker_controller.rb
app/views/worker/worker.html.erb
app/views/worker/worker_directory.html.erb
config/routes.rb
db/seeds.rb

Closes #6 
added route, controller action, and view template for worker directory; added view info link for individual workers to worker directory page; added back link to individual worker page to go back to the worker directory page

HANDY-12: Add a worker description page

---

config/routes.rb

Closes: #37 
How to Evaluate: the best way would be to run the application to see if the behavior is expected. You can also peep the routes file (app/config/routes.rb)

BUGFIX-2: Fix the re-route to customer home after worker sign-in and sign-up

---

app/views/customers/registrations/edit.html.erb

closes #52 
Added fields to edit customer profile information.

HANDY-32: Add functionality to edit customer profile

---

app/views/workers/registrations/edit.html.erb

closes #58 
Added fields to edit worker profile information.

HANDY-37: Add edit functionality to worker profile page

---

app/models/worker.rb
db/migrate/20211104213609_add_invisibility_to_workers.rb
db/schema.rb
db/seeds.rb
test/fixtures/workers.yml
test/models/worker_test.rb

closes #63 
Added invisibility attribute to worker devise model class.

HANDY-47: Add an "invisibility" to worker devise model class

---

app/controllers/job_controller.rb
app/views/customer/customer_profile.html.erb
app/views/job/edit.html.erb
app/views/job/my_jobs.html.erb
app/views/job/new.html.erb
config/routes.rb
db/seeds.rb

Added the ability for customers to edit their job postings. Had to add a separate page in the customer profile called my jobs. That is where customers can edit their pages.
closes #55

HANDY-35: Add edit functionality to existing job postings

---

app/controllers/job_controller.rb
app/views/layouts/application.html.erb
config/routes.rb
db/seeds.rb

closes #60 
Changed the find job button in the navbar to a dropdown menu filtering the jobs.

HANDY-42: change "find a job" button to be dropdown menu

---

app/controllers/worker_controller.rb
app/views/worker/worker_directory.html.erb
db/seeds.rb

Added sort by and alphabetical filter to worker directory.

HANDY-51: add a "alphabetical" filter to the worker directory

---

app/views/workers/registrations/edit.html.erb
app/views/workers/registrations/new.html.erb

Changed worker specialty text field to select dropdown in edit profile and sign-up pages.

HANDY-37-2: Changed worker specialty text field to select dropdown

---

app/controllers/application_controller.rb
app/views/worker/worker_directory.html.erb
app/views/workers/registrations/edit.html.erb
test/models/worker_test.rb

Closes: #65 
Task Outcome: Finished as planned.

HANDY-48: Add functionality to allow workers to be removed from the worker directory

---

app/controllers/application_controller.rb

Closes: #46 
Task Outcome: Completed as planned. There were also other bugs resolved with this fix. Such as, when a worker edited their profile, on submitting changes they would be re-directed to the customer home page instead of the worker home page. I added functions to the application controller that sets the customer and worker root path (home_path and worker_home_path respectively).

BUGFIX-4: A re-route issue exists when worker signs in

---

app/assets/stylesheets/application.scss
app/helpers/application_helper.rb
app/views/layouts/application.html.erb

Closes: #92 
Task Outcome: Completed as planned. 
How to evaluate: You can test out the different actions a user takes. Try logging in with incorrect credentials. Try creating/editing/deleting different objects

HANDY-45: Add simple bootstrap flash notifications to the application

---

app/controllers/worker_controller.rb
app/views/worker/search.erb
app/views/worker/worker_directory.html.erb

Closes: #51 
task Outcome: completed as planned
how to Evaluate: Test the functionality of the search bar added. Check the corresponding controller action as well for bugs

HANDY-13: Add functionality to search for worker by "type"

---

app/controllers/job_controller.rb
app/views/job/job_search.erb
app/views/layouts/application.html.erb
config/routes.rb

added search bar to the worker home page so the worker can search for a job by specialty.
closes #68

HANDY-38: Add a search bar to the worker Navbar #68

---

app/assets/stylesheets/application.scss
app/controllers/worker_controller.rb
app/views/worker/_no_workers_table_data.html.erb
app/views/worker/search.erb
app/views/worker/worker_directory.html.erb

closes #108 
changed table header color
added grey background to table
added filter to container

HANDY-54: Styled Worker Directory

---

app/models/message.rb
app/models/worker.rb
db/migrate/20211203182250_create_messages.rb
db/schema.rb
db/seeds.rb
test/fixtures/messages.yml
test/models/message_test.rb

Added a message model class to the application.

HANDY-46: Add a message model class to the application

---

app/models/customer.rb

Closes: #118 
Task Outome: completed as planned
How to Evaluate: Check the customer.rb file for two has_many() methods. Make sure they are working as expected.

HANDY-46-2: Added the relevant code customer.rb to associate customer class with message class

---

app/views/customer/home.html.erb
app/views/users/_welcome_message.html.erb
app/views/worker/worker_home.html.erb

Closes: #116 
Task Outcome: completed as planned. Noticed the buttons on the home page (when signed in) did not match the buttons when signed out. Fixed that.
How to Evaluate: Test it out by running the application. View both of the home pages while signed in and out.

HANDY-10-2: Change the "hi message" from a button to plain text.

---

app/views/job/my_jobs.html.erb

closes #120 
Added the delete button to the my_jobs view.

HANDY-55: Add the delete button to the my_jobs view

---

app/views/customer/customer_profile.html.erb
app/views/reviews/index.html.erb
app/views/worker/worker.html.erb
app/views/worker/worker_profile.html.erb

Closes: #96 
Task Outcome: completed as planned
How to Evaluate: check the app while running, the worker show page should be tidier, and their reviews are now on that page viewable by a collapse.

HANDY-11: Make the worker profile look a little tidier.
